// apps/web/src/features/meetings/components/bookings/BookingStepConfirm.vue
<script setup lang="ts">
import { ref } from 'vue'
import dayjs from 'dayjs'
import 'dayjs/locale/fr'
import { useFormErrorStore } from '@/stores/formErrorStore'
import { useRouter } from 'vue-router'
import type {
  BookingAnimal,
  BookingClinic,
  BookingVet,
  BookingSlot,
  SpecialityId,
} from '@armali/schemas'
import { meetingApi } from '@/features/meetings/api/meeting.api'
import { MEETING_COLORS } from '@/utils/meetingColor'
import { formatDate, subtractTime } from '../utils'

dayjs.locale('fr')

const props = defineProps<{
  animal: BookingAnimal
  clinic: BookingClinic
  vet: BookingVet
  slot: BookingSlot
  reason?: string
  specialityId?: SpecialityId | null
}>()

const emit = defineEmits<{ confirmed: [] }>()

const formError = useFormErrorStore()
const router = useRouter()
const confirming = ref(false)
const confirmed = ref(false)

async function confirm() {
  confirming.value = true
  formError.clear()
  try {
    await meetingApi.animal.new({
      animalId: props.animal.id,
      veterinarianId: props.vet.id,
      date: props.slot.date,
      startTime: props.slot.startTime,
      endTime: props.slot.endTime,
      specialityId: props.specialityId ?? null,
      description: props.reason || null,
      clinicId: props.clinic.id,
    })
    confirmed.value = true
    emit('confirmed')
  } catch (err) {
    formError.handle(err)
  } finally {
    confirming.value = false
  }
}
</script>

<template>
  <!-- Succès -->
  <div v-if="confirmed" class="success">
    <div class="success-icon">✅</div>
    <h2 class="success-title">Rendez-vous confirmé !</h2>
    <p class="success-desc">
      Un email de confirmation a été envoyé.<br />
      Vous pouvez retrouver ce rendez-vous dans votre espace.
    </p>
    <div class="success-actions">
      <el-button type="primary" @click="router.push('/meetings')">Voir mes rendez-vous</el-button>
      <el-button @click="router.push('/')">Retour à l'accueil</el-button>
    </div>
  </div>

  <!-- Résumé -->
  <template v-else>
    <div class="step">
      <div class="step-intro">
        <h2 class="step-title">Confirmez votre rendez-vous</h2>
        <p class="step-desc">Vérifiez les informations avant de confirmer.</p>
      </div>

      <div class="summary-card">
        <div class="summary-row">
          <span class="summary-label">Animal</span>
          <div class="summary-value">
            <span class="summary-main">{{ animal.name }}</span>
            <span class="summary-sub">{{ animal.race.pet.name }} · {{ animal.race.name }}</span>
          </div>
        </div>
        <div class="summary-divider" />
        <div class="summary-row">
          <span class="summary-label">Clinique</span>
          <div class="summary-value">
            <span class="summary-main">{{ clinic.name }}</span>
            <span class="summary-sub">{{ clinic.address }}</span>
          </div>
        </div>
        <div class="summary-divider" />
        <div class="summary-row">
          <span class="summary-label">Vétérinaire</span>
          <div class="summary-value">
            <span class="summary-main">Dr {{ vet.user.firstname }} {{ vet.user.lastname }}</span>
            <div class="vet-tags">
              <el-tag
                v-for="s in vet.specialities"
                :key="s.id"
                size="small"
                round
                :type="MEETING_COLORS.ANIMAL"
              >
                {{ s.name }}
              </el-tag>
            </div>
          </div>
        </div>
        <div class="summary-divider" />
        <div class="summary-row">
          <span class="summary-label">Date & heure</span>
          <div class="summary-value">
            <span class="summary-main summary-date">{{ formatDate(slot.date) }}</span>
            <span class="summary-sub">{{ subtractTime(slot.startTime, slot.endTime) }}</span>
          </div>
        </div>
        <template v-if="reason">
          <div class="summary-divider" />
          <div class="summary-row">
            <span class="summary-label">Motif</span>
            <span class="summary-main">{{ reason }}</span>
          </div>
        </template>
      </div>

      <el-alert
        type="info"
        :closable="false"
        show-icon
        title="Rappel"
        description="Les annulations sont possibles jusqu'à 48h avant le rendez-vous. Passé ce délai, contactez directement la clinique."
      />

      <el-button
        :type="MEETING_COLORS.ANIMAL"
        size="large"
        :loading="confirming"
        style="width: 100%"
        @click="confirm"
      >
        Confirmer le rendez-vous
      </el-button>
    </div>
  </template>
</template>

<style scoped lang="scss">
.step {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-xl);
}
.step-intro {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-xs);
}
.step-title {
  font-family: 'Nunito', sans-serif;
  font-size: 22px;
  font-weight: var(--fw-bold);
  color: var(--el-text-color-primary);
  margin: 0;
}
.step-desc {
  font-size: 14px;
  color: var(--el-text-color-secondary);
  margin: 0;
}
.summary-card {
  background: var(--el-bg-color);
  border: 1px solid var(--el-border-color-lighter);
  border-radius: var(--radius-xl);
  padding: var(--spacing-lg);
  display: flex;
  flex-direction: column;
  gap: var(--spacing-md);
}
.summary-row {
  display: flex;
  gap: var(--spacing-lg);
  align-items: flex-start;
}
.summary-label {
  font-size: 12px;
  font-weight: var(--fw-semibold);
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--el-text-color-placeholder);
  min-width: 100px;
  flex-shrink: 0;
  padding-top: 2px;
}
.summary-value {
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.summary-main {
  font-size: 15px;
  font-weight: var(--fw-semibold);
  color: var(--el-text-color-#{meeting-color('animal')});
}
.summary-date {
  color: var(--el-color-#{meeting-color('animal')});
}
.summary-sub {
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
.summary-divider {
  height: 1px;
  background: var(--el-border-color-lighter);
}
.vet-tags {
  display: flex;
  gap: 4px;
  flex-wrap: wrap;
  margin-top: 2px;
}
.success {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  gap: var(--spacing-lg);
  padding: var(--spacing-3xl) var(--spacing-xl);
}
.success-icon {
  font-size: 4rem;
}
.success-title {
  font-family: 'Nunito', sans-serif;
  font-size: 24px;
  font-weight: var(--fw-bold);
  color: var(--el-text-color-primary);
  margin: 0;
}
.success-desc {
  font-size: 15px;
  color: var(--el-text-color-secondary);
  line-height: 1.7;
  margin: 0;
}
.success-actions {
  display: flex;
  gap: var(--spacing-sm);
  flex-wrap: wrap;
  justify-content: center;
}
</style>

// apps/mobile/components/booking/BookingStepConfirm.tsx
import { useState } from "react";
import { ActivityIndicator, ScrollView, Text, TouchableOpacity, View } from "react-native";
import { ApiError, http } from "@/lib/api";
import { BookingAnimal, BookingClinic, BookingSlot, BookingVet } from "@/lib/booking-types";

type Props = {
  animal: BookingAnimal;
  clinic: BookingClinic;
  vet: BookingVet;
  slot: BookingSlot;
  specialityId: string | null;
  reason: string;
  onConfirmed: () => void;
};

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("fr-FR", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function formatTime(iso: string) {
  const d = new Date(iso);
  return `${d.getUTCHours()}h${d.getUTCMinutes().toString().padStart(2, "0")}`;
}

export default function BookingStepConfirm({
  animal,
  clinic,
  vet,
  slot,
  specialityId,
  reason,
  onConfirmed,
}: Props) {
  const [confirming, setConfirming] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [error, setError] = useState("");

  async function handleConfirm() {
    setConfirming(true);
    setError("");
    try {
      await http.post("/meetings/animals", {
        animalId: animal.id,
        veterinarianId: vet.id,
        clinicId: clinic.id,
        date: slot.date,
        startTime: slot.startTime,
        endTime: slot.endTime,
        specialityId: specialityId ?? null,
        description: reason || null,
      });
      setConfirmed(true);
    } catch (e: unknown) {
      setError(e instanceof ApiError ? e.message : "Une erreur est survenue. Veuillez réessayer.");
    } finally {
      setConfirming(false);
    }
  }

  if (confirmed) {
    return (
      <View className="flex-1 items-center justify-center px-6">
        <Text className="text-6xl mb-4">✅</Text>
        <Text className="text-xl font-bold text-gray-900 text-center">Rendez-vous confirmé !</Text>
        <Text className="text-gray-500 text-center mt-2">
          Un email de confirmation a été envoyé. Vous pouvez retrouver ce rendez-vous dans votre
          espace.
        </Text>
        <TouchableOpacity
          className="bg-primary rounded-2xl py-4 px-8 items-center mt-8 shadow-md"
          onPress={onConfirmed}
        >
          <Text className="text-white font-semibold text-base">Voir mes rendez-vous</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <ScrollView className="flex-1" contentContainerStyle={{ padding: 16, gap: 16 }}>
      <Text className="text-xl font-bold text-gray-900">Confirmez votre rendez-vous</Text>

      <View className="bg-gray-50 rounded-2xl border border-gray-100 p-4 gap-3">
        <View>
          <Text className="text-gray-500 text-xs">Animal</Text>
          <Text className="text-gray-900 font-semibold">{animal.name}</Text>
          <Text className="text-gray-500 text-xs">
            {animal.race.pet.name} · {animal.race.name}
          </Text>
        </View>
        <View className="h-px bg-gray-200" />
        <View>
          <Text className="text-gray-500 text-xs">Clinique</Text>
          <Text className="text-gray-900 font-semibold">{clinic.name}</Text>
          <Text className="text-gray-500 text-xs">{clinic.address}</Text>
        </View>
        <View className="h-px bg-gray-200" />
        <View>
          <Text className="text-gray-500 text-xs">Vétérinaire</Text>
          <Text className="text-gray-900 font-semibold">
            Dr {vet.user.firstname} {vet.user.lastname}
          </Text>
          <Text className="text-gray-500 text-xs">
            {vet.specialities.map((s) => s.name).join(", ")}
          </Text>
        </View>
        <View className="h-px bg-gray-200" />
        <View>
          <Text className="text-gray-500 text-xs">Date &amp; heure</Text>
          <Text className="text-gray-900 font-semibold capitalize">{formatDate(slot.date)}</Text>
          <Text className="text-gray-500 text-xs">
            {formatTime(slot.startTime)} — {formatTime(slot.endTime)}
          </Text>
        </View>
        {reason ? (
          <>
            <View className="h-px bg-gray-200" />
            <View>
              <Text className="text-gray-500 text-xs">Motif</Text>
              <Text className="text-gray-900 font-semibold">{reason}</Text>
            </View>
          </>
        ) : null}
      </View>

      <View className="bg-blue-50 rounded-2xl p-4 border border-blue-100">
        <Text className="text-primary font-semibold text-sm mb-1">Rappel</Text>
        <Text className="text-gray-600 text-xs">
          Les annulations sont possibles jusqu&apos;à 48h avant le rendez-vous. Passé ce délai,
          contactez directement la clinique.
        </Text>
      </View>

      {error ? <Text className="text-danger text-sm">{error}</Text> : null}

      <TouchableOpacity
        className="bg-primary rounded-2xl py-4 items-center shadow-md"
        onPress={handleConfirm}
        disabled={confirming}
      >
        {confirming ? (
          <ActivityIndicator color="white" />
        ) : (
          <Text className="text-white font-semibold text-base">Confirmer le rendez-vous</Text>
        )}
      </TouchableOpacity>
    </ScrollView>
  );
}
