// apps/web/src/features/bookings/components/BookingStepAnimal.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useAuthStore } from '@/stores/authStore'
import { animalApi } from '@/features/animals/api'
import type { BookingAnimal, BookingSpeciality, SpecialityId } from '@armali/schemas'
import { specialityApi } from '@/features/specialities/speciality.api'

const authStore = useAuthStore()

const selectedAnimal = defineModel<BookingAnimal | null>('animal', { required: true })
const selectedSpecialityId = defineModel<SpecialityId | null>('specialityId', { required: true })
const reason = defineModel<string>('reason', { required: true })

const animals = ref<BookingAnimal[]>([])
const specialities = ref<BookingSpeciality[]>([])
const loading = ref(true)

async function load() {
  if (!authStore.user) return
  loading.value = true
  try {
    const [animalsData, specialitiesData] = await Promise.all([
      animalApi.getAll(),
      specialityApi.getAll(),
    ])
    animals.value = animalsData
    specialities.value = specialitiesData
  } finally {
    loading.value = false
  }
}

await load()

const VISIT_REASONS = [
  'Consultation générale',
  'Vaccination',
  'Suivi post-opératoire',
  'Urgence',
  'Bilan de santé',
  'Autre',
]
</script>

<template>
  <div class="step">
    <div class="step-intro">
      <h2 class="step-title">Pour quel animal ?</h2>
      <p class="step-desc">Sélectionnez l'animal concerné par ce rendez-vous.</p>
    </div>

    <div v-if="loading" class="loading">
      <el-skeleton :rows="3" animated />
    </div>

    <template v-else>
      <div class="animal-grid">
        <button
          v-for="animal in animals"
          :key="animal.id"
          class="animal-card"
          :class="{ 'animal-card--selected': selectedAnimal?.id === animal.id }"
          @click="selectedAnimal = animal"
        >
          <div class="animal-avatar">
            <span>🐾</span>
          </div>
          <div class="animal-info">
            <span class="animal-name">{{ animal.name }}</span>
            <span class="animal-race">{{ animal.race.pet.name }} · {{ animal.race.name }}</span>
          </div>
          <div v-if="selectedAnimal?.id === animal.id" class="animal-check">
            <el-icon><Check /></el-icon>
          </div>
        </button>

        <div v-if="animals.length === 0" class="empty-animals">
          <p>Vous n'avez pas encore d'animal enregistré.</p>
          <el-button type="primary" size="small" @click="$router.push('/animals/new')">
            Ajouter un animal
          </el-button>
        </div>
      </div>

      <div v-if="selectedAnimal" class="section">
        <h3 class="section-label">
          Motif de la visite
          <span class="optional">facultatif</span>
        </h3>
        <div class="reason-chips">
          <button
            v-for="r in VISIT_REASONS"
            :key="r"
            class="reason-chip"
            :class="{ 'reason-chip--selected': reason === r }"
            @click="reason = reason === r ? '' : r"
          >
            {{ r }}
          </button>
        </div>
        <el-input
          v-if="reason === 'Autre'"
          v-model="reason"
          type="textarea"
          :rows="2"
          placeholder="Décrivez le motif..."
          class="reason-input"
        />
      </div>

      <div v-if="selectedAnimal" class="section">
        <h3 class="section-label">
          Spécialité souhaitée
          <span class="optional">facultatif</span>
        </h3>
        <el-select
          v-model="selectedSpecialityId"
          placeholder="Toutes les spécialités"
          clearable
          style="width: 100%"
        >
          <el-option v-for="s in specialities" :key="s.id" :label="s.name" :value="s.id" />
        </el-select>
      </div>
    </template>
  </div>
</template>

<style scoped lang="scss">
.step {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-xl);
}
.step-intro {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-xs);
}
.step-title {
  font-family: 'Nunito', sans-serif;
  font-size: 22px;
  font-weight: var(--fw-bold);
  color: var(--el-text-color-primary);
  margin: 0;
}
.step-desc {
  font-size: 14px;
  color: var(--el-text-color-secondary);
  margin: 0;
}
.animal-grid {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-sm);
}
.animal-card {
  display: flex;
  align-items: center;
  gap: var(--spacing-md);
  padding: var(--spacing-md) var(--spacing-lg);
  border-radius: var(--radius-lg);
  border: 1.5px solid var(--el-border-color-lighter);
  background: var(--el-bg-color);
  cursor: pointer;
  transition: all 0.15s;
  text-align: left;
  font-family: 'DM Sans', sans-serif;
  width: 100%;
  &:hover {
    border-color: var(--el-color-primary-light-5);
    background: var(--el-color-primary-light-9);
  }
  &--selected {
    border-color: var(--el-color-primary);
    background: var(--el-color-primary-light-9);
  }
}
.animal-avatar {
  width: 48px;
  height: 48px;
  border-radius: var(--radius-full);
  background: var(--el-fill-color-light);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1.5rem;
  flex-shrink: 0;
}
.animal-info {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.animal-name {
  font-size: 15px;
  font-weight: var(--fw-semibold);
  color: var(--el-text-color-primary);
}
.animal-race {
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
.animal-check {
  color: var(--el-color-primary);
  font-size: 18px;
}
.section {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-sm);
}
.section-label {
  font-size: 13px;
  font-weight: var(--fw-semibold);
  color: var(--el-text-color-secondary);
  text-transform: uppercase;
  letter-spacing: 0.06em;
  margin: 0;
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
}
.optional {
  font-size: 10px;
  font-weight: var(--fw-regular);
  color: var(--el-text-color-placeholder);
  text-transform: none;
  letter-spacing: 0;
  background: var(--el-fill-color);
  padding: 2px 6px;
  border-radius: var(--radius-full);
}
.reason-chips {
  display: flex;
  flex-wrap: wrap;
  gap: var(--spacing-xs);
}
.reason-chip {
  padding: 6px 14px;
  border-radius: var(--radius-full);
  border: 1px solid var(--el-border-color);
  background: var(--el-bg-color);
  font-family: 'DM Sans', sans-serif;
  font-size: 13px;
  color: var(--el-text-color-regular);
  cursor: pointer;
  transition: all 0.15s;
  &:hover {
    border-color: var(--el-color-primary-light-5);
    color: var(--el-color-primary);
  }
  &--selected {
    border-color: var(--el-color-primary);
    background: var(--el-color-primary-light-9);
    color: var(--el-color-primary);
    font-weight: var(--fw-medium);
  }
}
.reason-input {
  margin-top: var(--spacing-xs);
}
.empty-animals {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--spacing-sm);
  padding: var(--spacing-2xl);
  border: 1px dashed var(--el-border-color);
  border-radius: var(--radius-lg);
  text-align: center;
  p {
    font-size: 14px;
    color: var(--el-text-color-secondary);
    margin: 0;
  }
}
.loading {
  padding: var(--spacing-lg) 0;
}
</style>

// apps/mobile/components/booking/BookingStepAnimal.tsx
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, Text, TextInput, TouchableOpacity, View } from "react-native";
import { ApiError, http } from "@/lib/api";
import { BookingAnimal, REASON_CHIPS, Speciality } from "@/lib/booking-types";

type Props = {
  selectedAnimal: BookingAnimal | null;
  onSelectAnimal: (animal: BookingAnimal) => void;
  specialityId: string | null;
  onSelectSpeciality: (id: string | null) => void;
  reason: string;
  onChangeReason: (reason: string) => void;
};

export default function BookingStepAnimal({
  selectedAnimal,
  onSelectAnimal,
  specialityId,
  onSelectSpeciality,
  reason,
  onChangeReason,
}: Props) {
  const [animals, setAnimals] = useState<BookingAnimal[] | null>(null);
  const [specialities, setSpecialities] = useState<Speciality[]>([]);
  const [error, setError] = useState("");
  const [customReason, setCustomReason] = useState(
    REASON_CHIPS.includes(reason as (typeof REASON_CHIPS)[number]) ? "" : reason,
  );
  const [showCustom, setShowCustom] = useState(reason === "Autre" || (!!reason && !REASON_CHIPS.includes(reason as (typeof REASON_CHIPS)[number])));

  const load = useCallback(async () => {
    try {
      const [animalsData, specialitiesData] = await Promise.all([
        http.get<BookingAnimal[]>("/animals"),
        http.get<Speciality[]>("/specialities"),
      ]);
      setAnimals(animalsData);
      setSpecialities(specialitiesData);
    } catch (e: unknown) {
      setError(e instanceof ApiError ? e.message : "Impossible de charger vos animaux.");
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  function handleChip(chip: string) {
    if (chip === "Autre") {
      setShowCustom(true);
      onChangeReason(customReason);
      return;
    }
    setShowCustom(false);
    onChangeReason(reason === chip ? "" : chip);
  }

  if (animals === null) {
    return (
      <View className="flex-1 items-center justify-center">
        <ActivityIndicator color="#4873a2" />
      </View>
    );
  }

  return (
    <ScrollView className="flex-1" contentContainerStyle={{ padding: 16, gap: 16 }}>
      <View>
        <Text className="text-xl font-bold text-gray-900">Pour quel animal ?</Text>
        <Text className="text-gray-500 text-sm mt-1">
          Sélectionnez l&apos;animal concerné par ce rendez-vous.
        </Text>
      </View>

      {error ? <Text className="text-danger text-sm">{error}</Text> : null}

      {animals.length === 0 ? (
        <Text className="text-gray-500 text-center">
          Vous n&apos;avez pas encore d&apos;animal enregistré.
        </Text>
      ) : (
        <View className="gap-2">
          {animals.map((animal) => {
            const selected = selectedAnimal?.id === animal.id;
            return (
              <TouchableOpacity
                key={animal.id}
                className={`flex-row items-center gap-3 rounded-2xl p-3 border ${
                  selected ? "border-primary bg-blue-50" : "border-gray-100 bg-gray-50"
                }`}
                onPress={() => onSelectAnimal(animal)}
              >
                <Text className="text-2xl">🐾</Text>
                <View className="flex-1">
                  <Text className="text-gray-900 font-semibold">{animal.name}</Text>
                  <Text className="text-gray-500 text-xs">
                    {animal.race.pet.name} · {animal.race.name}
                  </Text>
                </View>
                {selected ? <Text className="text-primary text-lg">✓</Text> : null}
              </TouchableOpacity>
            );
          })}
        </View>
      )}

      <View>
        <View className="flex-row items-center gap-2 mb-2">
          <Text className="text-gray-900 font-semibold">Motif de la visite</Text>
          <View className="bg-gray-100 rounded-full px-2 py-0.5">
            <Text className="text-gray-500 text-xs">facultatif</Text>
          </View>
        </View>
        <View className="flex-row flex-wrap gap-2">
          {REASON_CHIPS.map((chip) => {
            const active = chip === "Autre" ? showCustom : reason === chip;
            return (
              <TouchableOpacity
                key={chip}
                className={`rounded-full px-3 py-1.5 border ${
                  active ? "bg-primary border-primary" : "bg-gray-50 border-gray-200"
                }`}
                onPress={() => handleChip(chip)}
              >
                <Text className={active ? "text-white text-sm" : "text-gray-700 text-sm"}>{chip}</Text>
              </TouchableOpacity>
            );
          })}
        </View>
        {showCustom ? (
          <TextInput
            className="border border-gray-200 rounded-2xl px-4 py-3 text-gray-900 bg-gray-50 mt-2"
            placeholder="Décrivez le motif..."
            placeholderTextColor="#9ca3af"
            value={customReason}
            onChangeText={(text) => {
              setCustomReason(text);
              onChangeReason(text);
            }}
            multiline
            numberOfLines={2}
          />
        ) : null}
      </View>

      <View>
        <View className="flex-row items-center gap-2 mb-2">
          <Text className="text-gray-900 font-semibold">Spécialité souhaitée</Text>
          <View className="bg-gray-100 rounded-full px-2 py-0.5">
            <Text className="text-gray-500 text-xs">facultatif</Text>
          </View>
        </View>
        <View className="flex-row flex-wrap gap-2">
          <TouchableOpacity
            className={`rounded-full px-3 py-1.5 border ${
              specialityId === null ? "bg-primary border-primary" : "bg-gray-50 border-gray-200"
            }`}
            onPress={() => onSelectSpeciality(null)}
          >
            <Text className={specialityId === null ? "text-white text-sm" : "text-gray-700 text-sm"}>
              Toutes les spécialités
            </Text>
          </TouchableOpacity>
          {specialities.map((s) => (
            <TouchableOpacity
              key={s.id}
              className={`rounded-full px-3 py-1.5 border ${
                specialityId === s.id ? "bg-primary border-primary" : "bg-gray-50 border-gray-200"
              }`}
              onPress={() => onSelectSpeciality(s.id)}
            >
              <Text className={specialityId === s.id ? "text-white text-sm" : "text-gray-700 text-sm"}>
                {s.name}
              </Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>
    </ScrollView>
  );
}
